# Generated by Django 5.2.6 on 2026-06-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_personaggio_tot_json'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
    ]
