# Generated by Django 5.2.15 on 2026-07-15 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0010_sort_inventory_by_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="EffettoPersonalizzato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=180)),
                ("tipo", models.CharField(blank=True, max_length=80)),
                ("descrizione", models.TextField(blank=True)),
                ("origine", models.CharField(blank=True, max_length=180)),
                ("icona", models.CharField(default="runa", max_length=80)),
                ("temporaneo", models.BooleanField(default=False)),
                ("ordine", models.PositiveIntegerField(default=0)),
                (
                    "personaggio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effetti_personalizzati",
                        to="characters.personaggio",
                    ),
                ),
            ],
            options={
                "ordering": ["ordine", "nome", "id"],
            },
        ),
        migrations.CreateModel(
            name="OperazioneEffettoPersonalizzato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordine", models.PositiveIntegerField(default=0)),
                ("bersaglio", models.CharField(max_length=80)),
                (
                    "operazione",
                    models.CharField(
                        choices=[
                            ("add", "Aggiungi"),
                            ("subtract", "Sottrai"),
                            ("multiply", "Moltiplica"),
                            ("percent", "Percentuale"),
                            ("min", "Valore minimo"),
                            ("max", "Valore massimo"),
                            ("cap", "Limite massimo"),
                            ("set", "Imposta"),
                            ("formula_override", "Sostituisci formula"),
                        ],
                        default="add",
                        max_length=32,
                    ),
                ),
                ("valore", models.TextField()),
                ("condizione", models.TextField(blank=True)),
                (
                    "effetto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operazioni",
                        to="characters.effettopersonalizzato",
                    ),
                ),
            ],
            options={
                "ordering": ["ordine", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="effettopersonalizzato",
            index=models.Index(
                fields=["personaggio", "ordine", "nome"],
                name="characters__persona_361fd6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="effettopersonalizzato",
            constraint=models.UniqueConstraint(
                fields=("personaggio", "nome"),
                name="unique_custom_effect_name_per_character",
            ),
        ),
        migrations.AddIndex(
            model_name="operazioneeffettopersonalizzato",
            index=models.Index(
                fields=["effetto", "ordine"], name="characters__effetto_d9f38a_idx"
            ),
        ),
    ]
