# Generated by Django 5.2.15 on 2026-07-17 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0012_remove_effettopersonalizzato_tipo_and_more"),
        ("core", "0009_famigliaskill_immagine_skill_azioni_attive_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillPersonaggio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("spesa_pe", models.JSONField(blank=True, default=dict)),
                ("passivi_accettati", models.JSONField(blank=True, default=list)),
                ("note", models.TextField(blank=True)),
                (
                    "personaggio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_sbloccate",
                        to="characters.personaggio",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personaggi_sbloccati",
                        to="core.skill",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "skill__famiglia__ordine",
                    "skill__ordine_famiglia",
                    "skill__nome",
                ],
                "indexes": [
                    models.Index(
                        fields=["personaggio", "skill"],
                        name="characters__persona_c406bd_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("personaggio", "skill"),
                        name="unique_skill_per_personaggio",
                    )
                ],
            },
        ),
    ]
