# Generated by Django 5.2.15 on 2026-07-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0013_skillpersonaggio"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillpersonaggio",
            name="configurazione_azioni",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
