# Generated by Django 5.2.15 on 2026-07-17 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0014_skillpersonaggio_configurazione_azioni"),
        ("core", "0010_alter_famigliaskill_gruppo"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="competenze",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="TiroCompetenza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("competence_key", models.CharField(max_length=80)),
                (
                    "technique",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("focus", "Impulso +4"),
                            ("amplify", "Risultato raddoppiato"),
                        ],
                        default="standard",
                        max_length=24,
                    ),
                ),
                ("die_sides", models.PositiveSmallIntegerField(default=6)),
                ("base_rank", models.SmallIntegerField(default=0)),
                ("manual_extra", models.SmallIntegerField(default=0)),
                ("linked_extra", models.SmallIntegerField(default=0)),
                ("modifier", models.SmallIntegerField(default=0)),
                ("focus_bonus", models.SmallIntegerField(default=0)),
                ("multiplier", models.PositiveSmallIntegerField(default=1)),
                ("energy_spent", models.PositiveSmallIntegerField(default=0)),
                ("rolls", models.JSONField(blank=True, default=list)),
                ("total", models.IntegerField(default=0)),
                ("rerolls_used", models.PositiveSmallIntegerField(default=0)),
                ("daily_marker", models.CharField(max_length=120)),
                (
                    "competenza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tiri",
                        to="core.competenze",
                    ),
                ),
                (
                    "personaggio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiri_competenze",
                        to="characters.personaggio",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["personaggio", "competence_key", "daily_marker"],
                        name="characters__persona_376482_idx",
                    ),
                    models.Index(
                        fields=["personaggio", "created_at"],
                        name="characters__persona_73c39f_idx",
                    ),
                ],
            },
        ),
    ]
