# Generated by Django 5.2.15 on 2026-07-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0016_alter_tirocompetenza_technique"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaggio",
            name="pa_spesi",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="personaggio",
            name="stanchezza_accumulata",
            field=models.IntegerField(default=0),
        ),
    ]
