# Generated by Django 5.2.15 on 2026-07-22 21:17

import django.db.models.deletion
from django.db import migrations, models


def assign_existing_characters_to_test_campaign(apps, schema_editor):
    Personaggio = apps.get_model("characters", "Personaggio")
    DatiCampagna = apps.get_model("core", "DatiCampagna")
    campaign = DatiCampagna.objects.filter(nome="Campagna Test").order_by("id").first()
    if campaign is not None:
        Personaggio.objects.filter(campagna__isnull=True).update(campagna=campaign)


def clear_test_campaign_assignment(apps, schema_editor):
    Personaggio = apps.get_model("characters", "Personaggio")
    DatiCampagna = apps.get_model("core", "DatiCampagna")
    campaign = DatiCampagna.objects.filter(nome="Campagna Test").order_by("id").first()
    if campaign is not None:
        Personaggio.objects.filter(campagna=campaign).update(campagna=None)


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0020_bottonecombat"),
        ("core", "0020_daticampagna_note_condivise_and_more"),
        ("media_library", "0004_uploadedimage_group_imagecategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaggio",
            name="campagna",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personaggi",
                to="core.daticampagna",
            ),
        ),
        migrations.AddField(
            model_name="personaggio",
            name="portrait",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personaggi_ritratto",
                to="media_library.uploadedimage",
            ),
        ),
        migrations.AlterField(
            model_name="personaggio",
            name="tipologia",
            field=models.CharField(
                choices=[
                    ("giocabile", "Giocabile"),
                    ("automatico", "Automatico"),
                    ("npc", "NPC"),
                    ("nemico", "Nemico"),
                    ("evocazione", "Evocazione"),
                    ("altro", "Altro"),
                ],
                default="npc",
                max_length=40,
            ),
        ),
        migrations.AddIndex(
            model_name="personaggio",
            index=models.Index(
                fields=["campagna", "tipologia", "nome"],
                name="characters__campagn_b26496_idx",
            ),
        ),
        migrations.RunPython(assign_existing_characters_to_test_campaign, clear_test_campaign_assignment),
    ]
