# Generated by Django 5.2.15 on 2026-07-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0025_drop_dead_mana_ratio_totals"),
    ]

    operations = [
        migrations.CreateModel(
            name="EffettoPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=180, unique=True)),
                ("descrizione", models.TextField(blank=True)),
                (
                    "origine",
                    models.CharField(blank=True, default="Preset", max_length=180),
                ),
                ("icona", models.CharField(default="effetto", max_length=80)),
                ("temporaneo", models.BooleanField(default=True)),
                ("categoria", models.CharField(blank=True, max_length=80)),
                ("ordine", models.PositiveIntegerField(default=0)),
                ("operazioni", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Preset effetto",
                "verbose_name_plural": "Preset effetto",
                "ordering": ["ordine", "nome", "id"],
                "indexes": [
                    models.Index(
                        fields=["categoria", "ordine"],
                        name="characters__categor_36835c_idx",
                    )
                ],
            },
        ),
    ]
