# Generated by Django 5.2.15 on 2026-07-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0028_retarget_tick_giallo_and_spasmi"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="furto",
            field=models.TextField(blank=True, default=""),
        ),
    ]
