# Generated by Django 5.2.15 on 2026-07-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0029_note_furto"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaggio",
            name="caratteristica_preferita",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
