export function GeneratorRulesEditor({ rules, onChange }: {
  rules: Record<string, unknown>;
  onChange: (value: Record<string, unknown>) => void;
}) {
  const update = (key: string, value: unknown) => onChange({ ...rules, [key]: value });
  const rarities = (rules.rarityProbabilities || {}) as Record<string, number>;
  const rarityTotal = Object.values(rarities).reduce((total, value) => total + Number(value || 0), 0);
  const fallbacks = (rules.fallbackLevelDeltas || []) as number[];
  return <div className="market-advanced-settings">
    <header><span>◆</span><div><strong>Regole globali del generatore</strong><small>Livelli, quantità, rarità, copie e prezzi di tutti i negozi.</small></div></header>
    <div className="market-rule-sections">
      <section><header><strong>Livelli</strong><small>Intervallo consentito e ricerca di alternative.</small></header><div className="market-rule-grid"><label>Livello minimo<input type="number" min="1" value={Number(rules.minLevel ?? 1)} onChange={(event) => update("minLevel", Number(event.target.value))} /></label><label>Livello massimo<input type="number" min="1" value={Number(rules.maxLevel ?? 10)} onChange={(event) => update("maxLevel", Number(event.target.value))} /></label></div><div className="market-fallback-levels"><span>Se manca il livello esatto:</span>{[-3, -2, -1, 0, 1, 2, 3].map((delta) => { const active = fallbacks.includes(delta); return <button type="button" key={delta} className={active ? "active" : ""} onClick={() => update("fallbackLevelDeltas", active ? fallbacks.filter((value) => value !== delta) : [...fallbacks, delta].sort((a, b) => Math.abs(a) - Math.abs(b) || a - b))}>{delta > 0 ? `+${delta}` : delta}</button>; })}</div></section>
      <section><header><strong>Quantità</strong><small>Formula base prima della dimensione e del profilo del negozio.</small></header><div className="market-rule-grid"><label>Oggetti base<input type="number" min="0" step=".5" value={Number(rules.baseCount ?? 0)} onChange={(event) => update("baseCount", Number(event.target.value))} /></label><label>Per livello<input type="number" min="0" step=".5" value={Number(rules.countPerLevel ?? 0)} onChange={(event) => update("countPerLevel", Number(event.target.value))} /></label><label>Varianza %<input type="number" min="0" max="100" value={Math.round(Number(rules.countVariance ?? 0) * 100)} onChange={(event) => update("countVariance", Number(event.target.value) / 100)} /></label><label>Copie massime<input type="number" min="1" value={Number(rules.maximumCopies ?? 1)} onChange={(event) => update("maximumCopies", Number(event.target.value))} /></label></div><p className="market-rule-formula">Stima: (base + livello × per livello) × tipo × profilo, con la varianza scelta.</p></section>
      <section><header><strong>Rarità di riserva</strong><small>Usate come base globale; i profili possono sostituirle.</small></header><div className="market-rarity-grid">{[["1", "Comune"], ["2", "Non comune"], ["3", "Raro"], ["4", "Pregiato"]].map(([key, label]) => <label key={key}>{label}<span><input type="number" min="0" max="100" value={Math.round(Number(rarities[key] || 0) * 100)} onChange={(event) => update("rarityProbabilities", { ...rarities, [key]: Number(event.target.value) / 100 })} />%</span></label>)}</div><p className={Math.abs(rarityTotal - 1) < .001 ? "market-rule-total valid" : "market-rule-total invalid"}>Totale: {Math.round(rarityTotal * 100)}%</p></section>
      <section><header><strong>Prezzi</strong><small>Calcolati sul valore catalogo, poi moltiplicati dal profilo.</small></header><div className="market-rule-grid"><label>Prezzo base %<input type="number" min="0" value={Number(rules.priceBasePercent ?? 0)} onChange={(event) => update("priceBasePercent", Number(event.target.value))} /></label><label>Per livello %<input type="number" min="0" value={Number(rules.priceLevelPercent ?? 0)} onChange={(event) => update("priceLevelPercent", Number(event.target.value))} /></label><label>Trattativa massima ±%<input type="number" min="0" max="100" value={Number(rules.maximumNegotiationPercent ?? 0)} onChange={(event) => update("maximumNegotiationPercent", Number(event.target.value))} /></label></div></section>
    </div>
  </div>;
}
