# Generated by Django 5.2.15 on 2026-06-16 12:50

import backend.media_library.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("media_library", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("title", models.CharField(max_length=180)),
                (
                    "file",
                    models.FileField(
                        upload_to=backend.media_library.models.v2_audio_upload_path
                    ),
                ),
                ("primary_tag", models.CharField(blank=True, max_length=80)),
                ("secondary_tags", models.JSONField(blank=True, default=list)),
                ("source", models.CharField(blank=True, max_length=80)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["primary_tag", "title"],
            },
        ),
        migrations.CreateModel(
            name="DatiMappa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=180)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("globale", "Globale"),
                            ("viaggio", "Viaggio"),
                            ("combattimento", "Combattimento"),
                            ("dungeon", "Dungeon"),
                            ("altro", "Altro"),
                        ],
                        default="altro",
                        max_length=40,
                    ),
                ),
                ("progressi", models.JSONField(blank=True, default=dict)),
                ("grid_data", models.JSONField(blank=True, default=dict)),
                ("markers", models.JSONField(blank=True, default=list)),
                ("hex_effects", models.JSONField(blank=True, default=dict)),
                ("canvas_state", models.JSONField(blank=True, default=dict)),
                ("dimensioni", models.JSONField(blank=True, default=dict)),
                ("default_for_campaign", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["tipo", "nome"],
            },
        ),
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("title", models.CharField(max_length=180)),
                ("folder", models.CharField(blank=True, max_length=160)),
                (
                    "file",
                    models.FileField(
                        upload_to=backend.media_library.models.v2_image_upload_path
                    ),
                ),
                (
                    "thumbnail",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=backend.media_library.models.v2_image_upload_path,
                    ),
                ),
                ("usage_type", models.CharField(default="generic", max_length=80)),
                ("is_default_for_usage", models.BooleanField(default=False)),
                ("source", models.CharField(blank=True, max_length=80)),
                ("prompt", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["folder", "title"],
            },
        ),
        migrations.RenameIndex(
            model_name="usermediaasset",
            new_name="media_libra_owner_i_635ac4_idx",
            old_name="media_libra_owner_i_ae20f2_idx",
        ),
        migrations.AddIndex(
            model_name="audiofile",
            index=models.Index(
                fields=["primary_tag", "title"], name="media_libra_primary_f52858_idx"
            ),
        ),
        migrations.AddField(
            model_name="datimappa",
            name="campagna",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mappe",
                to="core.daticampagna",
            ),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="campagna",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_images",
                to="core.daticampagna",
            ),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="media_library.uploadedimage",
            ),
        ),
        migrations.AddField(
            model_name="datimappa",
            name="fog_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fog_mappe",
                to="media_library.uploadedimage",
            ),
        ),
        migrations.AddField(
            model_name="datimappa",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mappe",
                to="media_library.uploadedimage",
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedimage",
            index=models.Index(
                fields=["usage_type", "is_default_for_usage"],
                name="media_libra_usage_t_a16554_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedimage",
            index=models.Index(
                fields=["campagna", "folder"], name="media_libra_campagn_e78176_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datimappa",
            index=models.Index(
                fields=["campagna", "tipo", "default_for_campaign"],
                name="media_libra_campagn_ebbe1d_idx",
            ),
        ),
    ]
