# Generated by Django 5.2.6 on 2026-06-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_delete_character'),
        ('media_library', '0002_audiofile_datimappa_uploadedimage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMediaAsset',
        ),
    ]
