# Generated by Django 5.2.15 on 2026-07-17 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_theme_energy_color_theme_health_color_and_more"),
        ("media_library", "0003_delete_usermediaasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="group",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name="ImageCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("usage_types", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "categoria immagine",
                "verbose_name_plural": "categorie immagini",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "order", "name"],
                        name="media_libra_is_acti_4aef18_idx",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="media_library.imagecategory",
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedimage",
            index=models.Index(
                fields=["category", "group", "title"],
                name="media_libra_categor_d4c3fe_idx",
            ),
        ),
    ]
