# Generated by Django 5.2.15 on 2026-07-31 11:51

import backend.media_library.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0006_audiofile_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoClip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("title", models.CharField(max_length=180)),
                (
                    "file",
                    models.FileField(
                        upload_to=backend.media_library.models.v2_video_upload_path
                    ),
                ),
                ("usage_type", models.CharField(default="generic", max_length=80)),
                ("source", models.CharField(blank=True, max_length=80)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "poster",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fotogramma statico mostrato prima della riproduzione.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_clips",
                        to="media_library.uploadedimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "clip video",
                "verbose_name_plural": "clip video",
                "ordering": ["usage_type", "title"],
                "indexes": [
                    models.Index(
                        fields=["usage_type", "title"],
                        name="media_libra_usage_t_1c0d41_idx",
                    )
                ],
            },
        ),
    ]
