"""Catalogo dei preset effetto ereditati da Elder Django.

Ogni voce descrive un effetto pronto all'uso: l'editor degli effetti la usa per
precompilare il modulo "Nuovo effetto". I preset senza operazioni restano
descrittivi: la regola vive nella descrizione e viene arbitrata al tavolo.
"""

from __future__ import annotations

from typing import Any


EFFECT_PRESET_CATEGORIES = ("Condizioni", "Malattie", "Cibo", "Bagni")


DEFAULT_EFFECT_PRESETS: tuple[dict[str, Any], ...] = (
    {
        "name": "Scosso",
        "description": "-3 attacco, 10% di sbagliare cast",
        "origin": "Preset",
        "icon": "effetto",
        "category": "Condizioni",
        "order": 1,
        "operations": [
            {"target": "attacco", "operation": "subtract", "value": "3", "condition": ""},
        ],
    },
    {
        "name": "Impaurito",
        "description": "+2 difesa, -6 attacco, 20% di sbagliare cast",
        "origin": "Preset",
        "icon": "effetto",
        "category": "Condizioni",
        "order": 2,
        "operations": [
            {"target": "difesa", "operation": "add", "value": "2", "condition": ""},
            {"target": "attacco", "operation": "subtract", "value": "6", "condition": ""},
        ],
    },
    {
        "name": "Sanguinante",
        "description": "-1 pf per turno per 5 turni, minimo 0 pf",
        "origin": "Preset",
        "icon": "effetto",
        "category": "Condizioni",
        "order": 3,
        "operations": [],
    },
    {
        "name": "Abbagliato/Penombra",
        "description": "Puoi attaccare solo entro 1m, oltre -20% errore per casella",
        "origin": "Preset",
        "icon": "effetto",
        "category": "Condizioni",
        "order": 4,
        "operations": [],
    },
    {
        "name": "Nauseato",
        "description": "Spendi il doppio di energia",
        "origin": "Preset",
        "icon": "effetto",
        "category": "Condizioni",
        "order": 5,
        "operations": [],
    },
    {
        "name": "Rallentato",
        "description": "Dimezza i punti azione disponibili",
        "origin": "Preset",
        "icon": "effetto",
        "category": "Condizioni",
        "order": 6,
        "operations": [
            {"target": "pa", "operation": "multiply", "value": "0.5", "condition": ""},
        ],
    },
    {
        "name": "Terrorizzato",
        "description": "Fuggi, se non puoi combatti usando tutte le risorse",
        "origin": "Preset",
        "icon": "effetto",
        "category": "Condizioni",
        "order": 7,
        "operations": [],
    },
    {
        "name": "Accecato/Buio",
        "description": "50% di fallire colpi o cast entro 1m, oltre 100%",
        "origin": "Preset",
        "icon": "effetto",
        "category": "Condizioni",
        "order": 8,
        "operations": [],
    },
    {
        "name": "Muto",
        "description": "Non puoi parlare, dare comandi agli animali, etc.",
        "origin": "Preset",
        "icon": "effetto",
        "category": "Condizioni",
        "order": 9,
        "operations": [],
    },
    {
        "name": "Stordito",
        "description": "50% di fallire qualsiasi azione non di movimento",
        "origin": "Preset",
        "icon": "effetto",
        "category": "Condizioni",
        "order": 10,
        "operations": [],
    },
    {
        "name": "Paralizzato",
        "description": "Azzera i punti azione disponibili",
        "origin": "Preset",
        "icon": "effetto",
        "category": "Condizioni",
        "order": 11,
        "operations": [
            {"target": "pa", "operation": "set", "value": "0", "condition": ""},
        ],
    },
    {
        "name": "Comandato",
        "description": "Esegue ciò che decide l'autore dell'incantesimo",
        "origin": "Preset",
        "icon": "effetto",
        "category": "Condizioni",
        "order": 12,
        "operations": [],
    },
    {
        "name": "Frenetico",
        "description": "Attacca con tutte le risorse il pg o npc più vicino",
        "origin": "Preset",
        "icon": "effetto",
        "category": "Condizioni",
        "order": 13,
        "operations": [],
    },
    {
        "name": "Mindscaped",
        "description": "Mindscaped",
        "origin": "Preset",
        "icon": "effetto",
        "category": "Condizioni",
        "order": 14,
        "operations": [],
    },
    {
        "name": "Atassia",
        "description": "Non fai frasi di senso compiuto",
        "origin": "Preset",
        "icon": "malattia",
        "category": "Malattie",
        "order": 15,
        "operations": [],
    },
    {
        "name": "Brividi",
        "description": "15% di fallire azioni",
        "origin": "Preset",
        "icon": "malattia",
        "category": "Malattie",
        "order": 16,
        "operations": [],
    },
    {
        "name": "Vermi infetti",
        "description": "1 stanchezza ogni 12 ore",
        "origin": "Preset",
        "icon": "malattia",
        "category": "Malattie",
        "order": 17,
        "operations": [],
    },
    {
        "name": "Articolazioni di Roccia",
        "description": "-1 modifica generale",
        "origin": "Preset",
        "icon": "malattia",
        "category": "Malattie",
        "order": 18,
        "operations": [
            {"target": "modificatore_generale", "operation": "subtract", "value": "1", "condition": ""},
        ],
    },
    {
        "name": "Articolazioni Infernali",
        "description": "-2 modifica generale",
        "origin": "Preset",
        "icon": "malattia",
        "category": "Malattie",
        "order": 19,
        "operations": [
            {"target": "modificatore_generale", "operation": "subtract", "value": "2", "condition": ""},
        ],
    },
    {
        "name": "Demenza",
        "description": "Ogni turno, se fallisci tiro concentrazione 5, non fai azione",
        "origin": "Preset",
        "icon": "malattia",
        "category": "Malattie",
        "order": 20,
        "operations": [],
    },
    {
        "name": "Febbre Pesante",
        "description": "Raddoppia il costo in energia",
        "origin": "Preset",
        "icon": "malattia",
        "category": "Malattie",
        "order": 21,
        "operations": [],
    },
    {
        "name": "Sfuggimente",
        "description": "-4 intelligenza e concentrazione",
        "origin": "Preset",
        "icon": "malattia",
        "category": "Malattie",
        "order": 22,
        "operations": [
            {"target": "intelligenza", "operation": "subtract", "value": "4", "condition": ""},
            {"target": "concentrazione", "operation": "subtract", "value": "4", "condition": ""},
        ],
    },
    {
        "name": "Tick Giallo",
        "description": "-1 a tutte le abilità",
        "origin": "Preset",
        "icon": "malattia",
        "category": "Malattie",
        "order": 23,
        "operations": [
            {"target": "modificatore_generale", "operation": "subtract", "value": "1", "condition": ""},
        ],
    },
    {
        "name": "Spasmi",
        "description": "-1 a tutti i tiri",
        "origin": "Preset",
        "icon": "malattia",
        "category": "Malattie",
        "order": 24,
        "operations": [
            {"target": "modificatore_generale", "operation": "subtract", "value": "1", "condition": ""},
        ],
    },
    {
        "name": "C-Stufato di Carne",
        "description": "Uno stufato sostanzioso che aumenta la salute.",
        "origin": "Preset",
        "icon": "cibo",
        "category": "Cibo",
        "order": 25,
        "operations": [
            {"target": "pf", "operation": "add", "value": "personaggio.livello/1.5+5", "condition": ""},
        ],
    },
    {
        "name": "C-Spezzatino",
        "description": "Uno spezzatino ricco che ripristina salute e stamina.",
        "origin": "Preset",
        "icon": "cibo",
        "category": "Cibo",
        "order": 26,
        "operations": [
            {"target": "pf", "operation": "add", "value": "personaggio.livello+7", "condition": ""},
            {"target": "pa", "operation": "add", "value": "personaggio.livello/5+1", "condition": ""},
        ],
    },
    {
        "name": "C-Taglio Scelto",
        "description": "Un taglio di carne pregiato che aumenta significativamente salute e stamina.",
        "origin": "Preset",
        "icon": "cibo",
        "category": "Cibo",
        "order": 27,
        "operations": [
            {"target": "pf", "operation": "add", "value": "personaggio.livello*1.3+9", "condition": ""},
            {"target": "pa", "operation": "add", "value": "personaggio.livello/4+2", "condition": ""},
        ],
    },
    {
        "name": "C-Zuppa di Pesce",
        "description": "Una zuppa di pesce che ripristina il mana.",
        "origin": "Preset",
        "icon": "cibo",
        "category": "Cibo",
        "order": 28,
        "operations": [
            {"target": "mana", "operation": "add", "value": "personaggio.livello/1.5+5", "condition": ""},
        ],
    },
    {
        "name": "C-Pesce al Forno",
        "description": "Pesce al forno che ripristina mana e stamina.",
        "origin": "Preset",
        "icon": "cibo",
        "category": "Cibo",
        "order": 29,
        "operations": [
            {"target": "mana", "operation": "add", "value": "personaggio.livello+7", "condition": ""},
            {"target": "pa", "operation": "add", "value": "personaggio.livello/5+1", "condition": ""},
        ],
    },
    {
        "name": "C-Trancio di Pesce",
        "description": "Un grande trancio di pesce che aumenta notevolmente mana e stamina.",
        "origin": "Preset",
        "icon": "cibo",
        "category": "Cibo",
        "order": 30,
        "operations": [
            {"target": "mana", "operation": "add", "value": "personaggio.livello*1.3+9", "condition": ""},
            {"target": "pa", "operation": "add", "value": "personaggio.livello/4+2", "condition": ""},
        ],
    },
    {
        "name": "C-Stufato di Verdure",
        "description": "Uno stufato di verdure che ripristina energia.",
        "origin": "Preset",
        "icon": "cibo",
        "category": "Cibo",
        "order": 31,
        "operations": [
            {"target": "energia", "operation": "add", "value": "personaggio.livello/1.5+5", "condition": ""},
        ],
    },
    {
        "name": "C-Zuppa di Legumi",
        "description": "Una zuppa di legumi che ripristina energia e stamina.",
        "origin": "Preset",
        "icon": "cibo",
        "category": "Cibo",
        "order": 32,
        "operations": [
            {"target": "energia", "operation": "add", "value": "personaggio.livello+7", "condition": ""},
            {"target": "pa", "operation": "add", "value": "personaggio.livello/5+1", "condition": ""},
        ],
    },
    {
        "name": "C-Ratatouille",
        "description": "Un delizioso mix di verdure che aumenta notevolmente energia e stamina.",
        "origin": "Preset",
        "icon": "cibo",
        "category": "Cibo",
        "order": 33,
        "operations": [
            {"target": "energia", "operation": "add", "value": "personaggio.livello*1.3+9", "condition": ""},
            {"target": "pa", "operation": "add", "value": "personaggio.livello/4+2", "condition": ""},
        ],
    },
    {
        "name": "B-Bagno con Sali",
        "description": "Un bagno rilassante con sali per ripristinare l'energia.",
        "origin": "Preset",
        "icon": "cibo",
        "category": "Bagni",
        "order": 34,
        "operations": [
            {"target": "energia", "operation": "add", "value": "personaggio.livello/1.5+5", "condition": ""},
        ],
    },
    {
        "name": "B-Bagno Lussuoso",
        "description": "Un bagno lussuoso per rinfrescarsi e rinvigorirsi.",
        "origin": "Preset",
        "icon": "cibo",
        "category": "Bagni",
        "order": 35,
        "operations": [
            {"target": "energia", "operation": "add", "value": "personaggio.livello+7", "condition": ""},
        ],
    },
)
