# Generated by Django 5.2.15 on 2026-07-27 19:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0025_elder_quick_stat_fixed_adjustments"),
        ("media_library", "0005_uploadedimage_visibilita_limitata"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoReputazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("titolo", models.CharField(blank=True, default="", max_length=200)),
                ("motivo", models.TextField()),
                (
                    "modalita",
                    models.CharField(
                        choices=[
                            ("adjust", "Aggiungi o sottrai"),
                            ("set", "Imposta valore"),
                        ],
                        default="adjust",
                        max_length=16,
                    ),
                ),
                ("giorno_campagna", models.IntegerField(default=0)),
                (
                    "ora_campagna",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("visibile_ai_giocatori", models.BooleanField(default=True)),
                (
                    "registrato_da",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                (
                    "campagna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventi_reputazione",
                        to="core.daticampagna",
                    ),
                ),
            ],
            options={
                "ordering": ["giorno_campagna", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Fazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=160)),
                ("descrizione", models.TextField(blank=True, default="")),
                (
                    "reputazione_base",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(-100),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("ordine", models.PositiveSmallIntegerField(default=0)),
                (
                    "campagna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fazioni",
                        to="core.daticampagna",
                    ),
                ),
                (
                    "emblema",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fazioni_emblema",
                        to="media_library.uploadedimage",
                    ),
                ),
            ],
            options={
                "ordering": ["ordine", "nome"],
            },
        ),
        migrations.CreateModel(
            name="EffettoEventoReputazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta", models.IntegerField(default=0)),
                ("valore_assoluto", models.IntegerField(blank=True, null=True)),
                ("propagato", models.BooleanField(default=False)),
                ("ordine", models.PositiveSmallIntegerField(default=0)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effetti",
                        to="lore.eventoreputazione",
                    ),
                ),
                (
                    "fazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effetti_reputazione",
                        to="lore.fazione",
                    ),
                ),
            ],
            options={
                "ordering": ["ordine", "id"],
            },
        ),
        migrations.CreateModel(
            name="PersonaggioLore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=180)),
                ("ruolo", models.CharField(blank=True, default="", max_length=160)),
                ("descrizione", models.TextField(blank=True, default="")),
                ("visibile_ai_giocatori", models.BooleanField(default=True)),
                ("ordine", models.PositiveSmallIntegerField(default=0)),
                (
                    "campagna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lore_personaggi",
                        to="core.daticampagna",
                    ),
                ),
                (
                    "fazione",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personaggi",
                        to="lore.fazione",
                    ),
                ),
                (
                    "ritratto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lore_personaggi_ritratto",
                        to="media_library.uploadedimage",
                    ),
                ),
            ],
            options={
                "ordering": ["ordine", "nome"],
            },
        ),
        migrations.CreateModel(
            name="RelazioneFazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("coefficiente", models.FloatField(default=0.0)),
                (
                    "destinazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relazioni_entranti",
                        to="lore.fazione",
                    ),
                ),
                (
                    "origine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relazioni_uscenti",
                        to="lore.fazione",
                    ),
                ),
            ],
            options={
                "ordering": ["origine__ordine", "destinazione__ordine"],
            },
        ),
        migrations.AddIndex(
            model_name="eventoreputazione",
            index=models.Index(
                fields=["campagna", "giorno_campagna"],
                name="lore_evento_campagn_8ba3b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fazione",
            index=models.Index(
                fields=["campagna", "ordine"], name="lore_fazion_campagn_721ac6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fazione",
            constraint=models.UniqueConstraint(
                fields=("campagna", "nome"), name="unique_faction_name_per_campaign"
            ),
        ),
        migrations.AddConstraint(
            model_name="effettoeventoreputazione",
            constraint=models.UniqueConstraint(
                fields=("evento", "fazione"), name="unique_faction_per_reputation_event"
            ),
        ),
        migrations.AddIndex(
            model_name="personaggiolore",
            index=models.Index(
                fields=["campagna", "ordine"], name="lore_person_campagn_02830d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="personaggiolore",
            constraint=models.UniqueConstraint(
                fields=("campagna", "nome"),
                name="unique_lore_character_name_per_campaign",
            ),
        ),
        migrations.AddConstraint(
            model_name="relazionefazione",
            constraint=models.UniqueConstraint(
                fields=("origine", "destinazione"), name="unique_faction_relation_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="relazionefazione",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("origine", models.F("destinazione")), _negated=True
                ),
                name="faction_relation_not_self",
            ),
        ),
    ]
