# Generated by Django 5.2.15 on 2026-07-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_elder_quick_stat_fixed_adjustments"),
        ("lore", "0001_initial"),
        ("media_library", "0005_uploadedimage_visibilita_limitata"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fazione",
            name="unique_faction_name_per_campaign",
        ),
        migrations.RemoveConstraint(
            model_name="personaggiolore",
            name="unique_lore_character_name_per_campaign",
        ),
        migrations.AddConstraint(
            model_name="fazione",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("campagna", "nome"),
                name="unique_faction_name_per_campaign",
            ),
        ),
        migrations.AddConstraint(
            model_name="personaggiolore",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("campagna", "nome"),
                name="unique_lore_character_name_per_campaign",
            ),
        ),
    ]
