# Generated by Django 5.2.15 on 2026-07-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("chat", "Chat"), ("image", "Immagini")],
                        default="chat",
                        max_length=16,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("anthropic", "Anthropic Messages"),
                            ("openai_compatible", "Compatibile OpenAI"),
                            ("openai_image", "Immagini OpenAI"),
                            ("stable_diffusion", "Stable Diffusion locale"),
                        ],
                        default="anthropic",
                        max_length=32,
                    ),
                ),
                (
                    "auth_strategy",
                    models.CharField(
                        choices=[
                            ("api_key", "Chiave API"),
                            ("none", "Nessuna autenticazione"),
                        ],
                        default="api_key",
                        max_length=32,
                    ),
                ),
                ("base_url", models.CharField(blank=True, max_length=300)),
                ("model", models.CharField(blank=True, max_length=160)),
                ("secret_ciphertext", models.TextField(blank=True, editable=False)),
                ("options", models.JSONField(blank=True, default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "provider AI",
                "verbose_name_plural": "provider AI",
                "ordering": ["purpose", "order", "name"],
                "indexes": [
                    models.Index(
                        fields=["purpose", "is_enabled", "order"],
                        name="ai_aiprovid_purpose_7cbcf2_idx",
                    )
                ],
            },
        ),
    ]
