# Generated by Django 5.2.15 on 2026-07-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0006_expand_full_access_agent_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiagentprofile",
            name="routing_mode",
            field=models.CharField(
                choices=[("off", "Disattivato"), ("auto", "Automatico")],
                default="auto",
                help_text="Con «Automatico», una domanda con molti strumenti disponibili viene prima instradata a un sottoinsieme pertinente.",
                max_length=8,
            ),
        ),
    ]
