# Generated by Django 5.2.15 on 2026-07-18 18:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("characters", "0017_personaggio_pa_spesi_and_more"),
        ("core", "0012_seed_skill_pricing_config"),
        ("media_library", "0004_uploadedimage_group_imagecategory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CombatModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("attack", "Attacco"),
                            ("damage", "Danno"),
                            ("both", "Entrambi"),
                        ],
                        default="both",
                        max_length=12,
                    ),
                ),
                ("attack_bonus", models.SmallIntegerField(default=0)),
                ("damage_bonus", models.SmallIntegerField(default=0)),
                ("penetration_flat", models.SmallIntegerField(default=0)),
                ("penetration_percent", models.SmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#9c7b45",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Inserisci un colore esadecimale nel formato #RRGGBB.",
                                regex="^#[0-9a-fA-F]{6}$",
                            )
                        ],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "modificatore di combattimento",
                "verbose_name_plural": "modificatori di combattimento",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HexType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="nome"),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descrizione"),
                ),
                (
                    "movement_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="moltiplicatore movimento",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#76866a",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Inserisci un colore esadecimale nel formato #RRGGBB.",
                                regex="^#[0-9a-fA-F]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "impassable",
                    models.BooleanField(default=False, verbose_name="intransitabile"),
                ),
                ("active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "tipo di esagono",
                "verbose_name_plural": "tipi di esagono",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MapHex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("q", models.SmallIntegerField()),
                ("r", models.SmallIntegerField()),
                (
                    "overlay_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Inserisci un colore esadecimale nel formato #RRGGBB.",
                                regex="^#[0-9a-fA-F]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "overlay_opacity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.35"), max_digits=3
                    ),
                ),
                ("blocked", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["r", "q"],
            },
        ),
        migrations.CreateModel(
            name="MapType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="nome"),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descrizione"),
                ),
                (
                    "default_orientation",
                    models.CharField(
                        choices=[("pointy", "Punta in alto"), ("flat", "Lato in alto")],
                        default="pointy",
                        max_length=12,
                    ),
                ),
                (
                    "default_rows",
                    models.PositiveSmallIntegerField(
                        default=24,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "default_columns",
                    models.PositiveSmallIntegerField(
                        default=32,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "tipo di mappa di combattimento",
                "verbose_name_plural": "tipi di mappa di combattimento",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "name",
                    models.CharField(max_length=160, unique=True, verbose_name="nome"),
                ),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "blueprint",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Profilo versionato: attributi, totali, competenze, skill, equipaggiamento, inventario, faretra, effetti e note.",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="combat_character_templates",
                        to="media_library.uploadedimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "modello di personaggio",
                "verbose_name_plural": "modelli di personaggio",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MapHexTerrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "map_hex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terrain_links",
                        to="combat.maphex",
                    ),
                ),
                (
                    "terrain_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hex_links",
                        to="combat.hextype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="maphex",
            name="terrain_types",
            field=models.ManyToManyField(
                related_name="map_hexes",
                through="combat.MapHexTerrain",
                to="combat.hextype",
            ),
        ),
        migrations.CreateModel(
            name="MapMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=180, verbose_name="nome")),
                (
                    "orientation",
                    models.CharField(
                        choices=[("pointy", "Punta in alto"), ("flat", "Lato in alto")],
                        default="pointy",
                        max_length=12,
                    ),
                ),
                (
                    "rows",
                    models.PositiveSmallIntegerField(
                        default=24,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "columns",
                    models.PositiveSmallIntegerField(
                        default=32,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "hex_size",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("34.00"),
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("4"))
                        ],
                    ),
                ),
                (
                    "grid_offset_x",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "grid_offset_y",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "image_scale",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.000"),
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.05"))
                        ],
                    ),
                ),
                (
                    "image_offset_x",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "image_offset_y",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "viewport_scale",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.000"),
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.05"))
                        ],
                    ),
                ),
                (
                    "viewport_offset_x",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "viewport_offset_y",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "active_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_on_combat_maps",
                        to="characters.personaggio",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_combat_maps",
                        to="core.giocatore",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="combat_maps",
                        to="media_library.uploadedimage",
                    ),
                ),
                (
                    "map_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maps",
                        to="combat.maptype",
                    ),
                ),
            ],
            options={
                "verbose_name": "metadati mappa di combattimento",
                "verbose_name_plural": "metadati mappe di combattimento",
                "ordering": ["-updated_at", "name"],
            },
        ),
        migrations.AddField(
            model_name="maphex",
            name="map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hexes",
                to="combat.mapmetadata",
            ),
        ),
        migrations.CreateModel(
            name="CombatModifierState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="combat.combatmodifier",
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifier_states",
                        to="combat.mapmetadata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CombatEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=80)),
                ("message", models.CharField(max_length=500)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="combat_events",
                        to="characters.personaggio",
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="combat.mapmetadata",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="MapParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                ("anchor_q", models.SmallIntegerField(default=0)),
                ("anchor_r", models.SmallIntegerField(default=0)),
                (
                    "token_color",
                    models.CharField(
                        default="#d6a64b",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Inserisci un colore esadecimale nel formato #RRGGBB.",
                                regex="^#[0-9a-fA-F]{6}$",
                            )
                        ],
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combat_map_participations",
                        to="characters.personaggio",
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="combat.mapmetadata",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MapParticipantFootprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "q",
                    models.SmallIntegerField(
                        default=0, help_text="Scostamento assiale dall'ancora"
                    ),
                ),
                (
                    "r",
                    models.SmallIntegerField(
                        default=0, help_text="Scostamento assiale dall'ancora"
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footprint",
                        to="combat.mapparticipant",
                    ),
                ),
            ],
            options={
                "ordering": ["r", "q"],
            },
        ),
        migrations.CreateModel(
            name="TurnPlanAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("movement", "Movimento"),
                            ("attack", "Attacco"),
                            ("cast", "Incantesimo"),
                            ("power", "Potere"),
                            ("other", "Altro"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("cost_pf", models.PositiveIntegerField(default=0)),
                ("cost_mana", models.PositiveIntegerField(default=0)),
                ("cost_energy", models.PositiveIntegerField(default=0)),
                ("cost_power", models.PositiveIntegerField(default=0)),
                ("cost_ap", models.PositiveIntegerField(default=0)),
                ("cost_fatigue", models.PositiveIntegerField(default=0)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combat_planned_actions",
                        to="characters.personaggio",
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_actions",
                        to="combat.mapmetadata",
                    ),
                ),
                (
                    "source_skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="combat_plan_actions",
                        to="core.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TurnPlanStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("q", models.SmallIntegerField()),
                ("r", models.SmallIntegerField()),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path",
                        to="combat.turnplanaction",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="maphexterrain",
            constraint=models.UniqueConstraint(
                fields=("map_hex", "terrain_type"), name="combat_unique_hex_terrain"
            ),
        ),
        migrations.AddConstraint(
            model_name="maphex",
            constraint=models.UniqueConstraint(
                fields=("map", "q", "r"), name="combat_unique_map_hex"
            ),
        ),
        migrations.AddConstraint(
            model_name="combatmodifierstate",
            constraint=models.UniqueConstraint(
                fields=("map", "modifier"), name="combat_unique_map_modifier"
            ),
        ),
        migrations.AddIndex(
            model_name="combatevent",
            index=models.Index(
                fields=["map", "id"], name="combat_comb_map_id_5e82e4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mapparticipant",
            constraint=models.UniqueConstraint(
                fields=("map", "character"), name="combat_unique_map_character"
            ),
        ),
        migrations.AddConstraint(
            model_name="mapparticipantfootprint",
            constraint=models.UniqueConstraint(
                fields=("participant", "q", "r"), name="combat_unique_footprint_cell"
            ),
        ),
        migrations.AddIndex(
            model_name="mapmetadata",
            index=models.Index(
                fields=["is_default", "updated_at"],
                name="combat_mapm_is_defa_724c4d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="turnplanstep",
            constraint=models.UniqueConstraint(
                fields=("action", "order"), name="combat_unique_plan_step"
            ),
        ),
    ]
