# Generated by Django 5.2.15 on 2026-07-18 20:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("combat", "0001_initial"),
        ("core", "0012_seed_skill_pricing_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="maphex",
            name="revealed",
            field=models.BooleanField(
                default=False, verbose_name="rivelato ai giocatori"
            ),
        ),
        migrations.AddField(
            model_name="mapmetadata",
            name="fog_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Quando attiva, gli esagoni non rivelati restano nascosti ai giocatori.",
                verbose_name="nebbia di guerra attiva",
            ),
        ),
        migrations.AddField(
            model_name="mapmetadata",
            name="fog_opacity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.88"),
                max_digits=3,
                verbose_name="opacita nebbia",
            ),
        ),
        migrations.CreateModel(
            name="MapSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("label", models.CharField(blank=True, max_length=180)),
                ("state", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="combat_map_snapshots",
                        to="core.giocatore",
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="combat.mapmetadata",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["map", "id"], name="combat_maps_map_id_e6a17f_idx"
                    )
                ],
            },
        ),
    ]
