# Generated by Django 5.2.15 on 2026-06-16 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competenze",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=160, unique=True)),
                ("descrizione", models.TextField(blank=True)),
                ("mapping_tag", models.JSONField(blank=True, default=dict)),
                ("ordine", models.IntegerField(default=0)),
                ("categoria", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "ordering": ["ordine", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Curiosita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=180, unique=True)),
                ("descrizione", models.TextField(blank=True)),
                ("categoria", models.CharField(blank=True, max_length=80)),
                ("visibile", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["categoria", "nome"],
            },
        ),
        migrations.CreateModel(
            name="EffettiEMalattie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("tipo", models.CharField(blank=True, max_length=80)),
                ("nome", models.CharField(max_length=180, unique=True)),
                ("descrizione", models.TextField(blank=True)),
                ("effect_payload", models.JSONField(blank=True, default=dict)),
                ("default_duration_turns", models.IntegerField(blank=True, null=True)),
                ("stacking_rule", models.CharField(blank=True, max_length=80)),
                ("icon", models.CharField(blank=True, max_length=160)),
            ],
            options={
                "ordering": ["tipo", "nome"],
            },
        ),
        migrations.CreateModel(
            name="FamigliaSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=160, unique=True)),
                ("gruppo", models.CharField(blank=True, max_length=80)),
                ("ordine", models.IntegerField(default=0)),
                ("is_classe", models.BooleanField(default=False)),
                ("is_religione", models.BooleanField(default=False)),
                ("is_perk", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                ("note_addizionali", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["ordine", "nome"],
            },
        ),
        migrations.CreateModel(
            name="GlobalModifiers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("value_float", models.JSONField(blank=True, default=dict)),
                ("value_string", models.JSONField(blank=True, default=dict)),
                ("rule_notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NomiRazzeInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=160, unique=True)),
                ("race", models.CharField(blank=True, max_length=120)),
                ("names_male", models.JSONField(blank=True, default=list)),
                ("names_female", models.JSONField(blank=True, default=list)),
                ("surnames", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["race", "name"],
            },
        ),
        migrations.CreateModel(
            name="TipoArma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=120, unique=True)),
                ("lunghezza", models.CharField(blank=True, max_length=80)),
                ("potenza", models.CharField(blank=True, max_length=80)),
                ("bonus_1", models.CharField(blank=True, max_length=160)),
                ("bonus_2", models.CharField(blank=True, max_length=160)),
                ("rules", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="CampaignLoreEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("tipo", models.CharField(blank=True, max_length=80)),
                ("slug", models.SlugField(max_length=180)),
                ("nome", models.CharField(max_length=180)),
                ("sommario", models.TextField(blank=True)),
                ("contenuto", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("aliases", models.JSONField(blank=True, default=list)),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("canon", "Canon"),
                            ("rumor", "Rumor"),
                            ("deprecated", "Deprecated"),
                            ("draft", "Draft"),
                            ("contradicted", "Contradicted"),
                        ],
                        default="canon",
                        max_length=40,
                    ),
                ),
                (
                    "visibilita",
                    models.CharField(
                        choices=[
                            ("dm", "DM only"),
                            ("player", "Player visible"),
                            ("mixed", "Mixed"),
                        ],
                        default="dm",
                        max_length=40,
                    ),
                ),
            ],
            options={
                "ordering": ["tipo", "nome"],
            },
        ),
        migrations.CreateModel(
            name="DatiCampagna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=160)),
                ("attiva", models.BooleanField(default=False)),
                ("meteo", models.CharField(blank=True, max_length=120)),
                ("ora_corrente", models.CharField(blank=True, max_length=80)),
                ("giorni_da_inizio", models.IntegerField(default=0)),
                ("risorse_speciali", models.JSONField(blank=True, default=dict)),
                ("state", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-attiva", "nome"],
            },
        ),
        migrations.CreateModel(
            name="CampaignLoreRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("relation_type", models.CharField(max_length=80)),
                ("relevance", models.IntegerField(default=0)),
                ("activation_context", models.JSONField(blank=True, default=dict)),
                ("note", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="core.campaignloreentry",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="core.campaignloreentry",
                    ),
                ),
                (
                    "campagna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lore_relations",
                        to="core.daticampagna",
                    ),
                ),
            ],
            options={
                "ordering": ["-relevance", "relation_type"],
            },
        ),
        migrations.AddField(
            model_name="campaignloreentry",
            name="campagna",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lore_entries",
                to="core.daticampagna",
            ),
        ),
        migrations.CreateModel(
            name="Giocatore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=120, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("password_hash", models.CharField(blank=True, max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("dm", "DM"),
                            ("player", "Player"),
                            ("guest", "Guest"),
                        ],
                        default="player",
                        max_length=20,
                    ),
                ),
                ("character_ids", models.JSONField(blank=True, default=list)),
                ("dice_profile", models.CharField(blank=True, max_length=120)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("notes", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Guida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=180, unique=True)),
                ("contenuto", models.TextField(blank=True)),
                ("categoria", models.CharField(blank=True, max_length=80)),
                ("ordine", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["ordine", "nome"],
            },
        ),
        migrations.CreateModel(
            name="HallOfFameCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=180)),
                ("campaign", models.CharField(blank=True, max_length=160)),
                ("descrizione", models.TextField(blank=True)),
                ("ordine", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["ordine", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Messaggio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("thread_key", models.CharField(blank=True, max_length=120)),
                ("content", models.TextField()),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("message_type", models.CharField(default="chat", max_length=40)),
                (
                    "campagna",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messaggi",
                        to="core.daticampagna",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_messages",
                        to="core.giocatore",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="core.giocatore",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Negozio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=180)),
                ("proprietario", models.CharField(blank=True, max_length=180)),
                ("categoria", models.CharField(blank=True, max_length=80)),
                ("livello", models.IntegerField(default=1)),
                ("regione_nome", models.CharField(blank=True, max_length=120)),
                ("regione_descrizione", models.TextField(blank=True)),
                ("citta_nome", models.CharField(blank=True, max_length=120)),
                ("citta_descrizione", models.TextField(blank=True)),
                ("lista_oggetti", models.JSONField(blank=True, default=list)),
                ("generation_seed", models.CharField(blank=True, max_length=120)),
                ("descrizione", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["regione_nome", "citta_nome", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=180, unique=True)),
                ("numero", models.IntegerField(unique=True)),
                ("ordine_famiglia", models.IntegerField(default=0)),
                ("magia", models.BooleanField(default=False)),
                ("costo_pe", models.IntegerField(default=0)),
                ("tipo_pe", models.CharField(blank=True, max_length=40)),
                ("costo_testuale", models.CharField(blank=True, max_length=255)),
                ("descrizione", models.TextField(blank=True)),
                ("requisiti", models.TextField(blank=True)),
                ("livello_magia", models.CharField(blank=True, max_length=80)),
                ("raggio", models.CharField(blank=True, max_length=120)),
                ("formula_effetto", models.CharField(blank=True, max_length=255)),
                ("profile_tags", models.JSONField(blank=True, default=dict)),
                ("profile_notes", models.TextField(blank=True)),
                ("note", models.TextField(blank=True)),
                (
                    "famiglia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="skills",
                        to="core.famigliaskill",
                    ),
                ),
            ],
            options={
                "ordering": ["famiglia__ordine", "ordine_famiglia", "numero", "nome"],
            },
        ),
        migrations.CreateModel(
            name="EffettiSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=180)),
                (
                    "fonte_tipo",
                    models.CharField(
                        choices=[
                            ("skill", "Skill"),
                            ("razza", "Razza"),
                            ("subrazza", "Subrazza"),
                            ("manuale", "Manuale"),
                            ("unit", "Unit"),
                            ("oggetto", "Oggetto"),
                        ],
                        default="skill",
                        max_length=40,
                    ),
                ),
                ("fonte_nome", models.CharField(blank=True, max_length=180)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("passivo", "Passivo"),
                            ("attivabile", "Attivabile"),
                            ("ibrido", "Ibrido"),
                        ],
                        default="passivo",
                        max_length=40,
                    ),
                ),
                ("descrizione", models.TextField(blank=True)),
                ("note_proposte", models.TextField(blank=True)),
                ("costi", models.JSONField(blank=True, default=dict)),
                ("durata_turni", models.IntegerField(blank=True, null=True)),
                ("messaggi", models.JSONField(blank=True, default=dict)),
                ("icona", models.CharField(blank=True, max_length=160)),
                ("effect_payload", models.JSONField(blank=True, default=dict)),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="effetti",
                        to="core.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=180)),
                ("data_evento", models.CharField(blank=True, max_length=80)),
                ("descrizione", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "campagna",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeline",
                        to="core.daticampagna",
                    ),
                ),
            ],
            options={
                "ordering": ["data_evento", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Oggetto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=180, unique=True)),
                ("modello", models.BooleanField(default=True)),
                ("temporaneo", models.BooleanField(default=False)),
                ("archiviato", models.BooleanField(default=False)),
                ("numero_ordine", models.IntegerField(blank=True, null=True)),
                ("icona", models.CharField(blank=True, max_length=160)),
                ("tipo_1", models.CharField(blank=True, max_length=80)),
                ("tipo_2", models.CharField(blank=True, max_length=80)),
                ("tipo_3", models.CharField(blank=True, max_length=80)),
                ("tipo_4", models.CharField(blank=True, max_length=80)),
                ("tipo_5", models.CharField(blank=True, max_length=80)),
                ("tipo_6", models.CharField(blank=True, max_length=80)),
                ("descrizione", models.TextField(blank=True)),
                ("valore", models.IntegerField(blank=True, null=True)),
                ("peso", models.FloatField(blank=True, null=True)),
                ("rarita", models.IntegerField(blank=True, null=True)),
                ("lv_loot", models.CharField(blank=True, max_length=80)),
                ("regione_loot", models.CharField(blank=True, max_length=120)),
                ("peso_regione", models.FloatField(blank=True, null=True)),
                ("pa_per_attacco", models.IntegerField(blank=True, null=True)),
                ("effects", models.JSONField(blank=True, default=list)),
                ("alchemy_profile", models.JSONField(blank=True, default=dict)),
                ("crafting_profile", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "tipo_arma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="oggetti",
                        to="core.tipoarma",
                    ),
                ),
            ],
            options={
                "ordering": ["numero_ordine", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=180, unique=True)),
                ("razza", models.CharField(blank=True, max_length=120)),
                ("categoria", models.CharField(blank=True, max_length=80)),
                ("archetipo_key", models.CharField(blank=True, max_length=120)),
                ("archetipo_tags", models.JSONField(blank=True, default=dict)),
                ("archetipo_descrizione", models.TextField(blank=True)),
                ("profilo_equip", models.CharField(blank=True, max_length=160)),
                ("profilo_competenze", models.JSONField(blank=True, default=dict)),
                ("levels", models.JSONField(blank=True, default=list)),
                ("preset", models.CharField(blank=True, max_length=80)),
                ("equipment_profiles", models.JSONField(blank=True, default=dict)),
                ("stat_profiles", models.JSONField(blank=True, default=dict)),
                ("skill_actions", models.JSONField(blank=True, default=list)),
                ("skill_unlocks", models.JSONField(blank=True, default=list)),
                ("lore_description", models.TextField(blank=True)),
                ("generation_rules", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["categoria", "razza", "nome"],
            },
        ),
        migrations.AddIndex(
            model_name="daticampagna",
            index=models.Index(
                fields=["attiva", "nome"], name="core_datica_attiva_dfb80d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignlorerelation",
            index=models.Index(
                fields=["campagna", "relation_type", "relevance"],
                name="core_campai_campagn_702b15_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignloreentry",
            index=models.Index(
                fields=["campagna", "tipo", "stato"],
                name="core_campai_campagn_d027f8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignloreentry",
            constraint=models.UniqueConstraint(
                fields=("campagna", "slug"), name="unique_lore_slug_per_campaign"
            ),
        ),
        migrations.AddIndex(
            model_name="giocatore",
            index=models.Index(
                fields=["role", "nome"], name="core_giocat_role_84310e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messaggio",
            index=models.Index(
                fields=["campagna", "thread_key", "created_at"],
                name="core_messag_campagn_05af70_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="negozio",
            index=models.Index(
                fields=["regione_nome", "citta_nome", "categoria"],
                name="core_negozi_regione_ec5bb5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["magia", "tipo_pe"], name="core_skill_magia_a5631a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["famiglia", "ordine_famiglia"],
                name="core_skill_famigli_581a13_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="effettiskill",
            index=models.Index(
                fields=["fonte_tipo", "tipo", "nome"],
                name="core_effett_fonte_t_2cea12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["campagna", "data_evento"],
                name="core_timeli_campagn_928739_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="oggetto",
            index=models.Index(
                fields=["modello", "archiviato"], name="core_oggett_modello_771031_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oggetto",
            index=models.Index(
                fields=["tipo_1", "tipo_2"], name="core_oggett_tipo_1_72f694_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oggetto",
            index=models.Index(
                fields=["regione_loot", "rarita"], name="core_oggett_regione_94a663_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["categoria", "razza"], name="core_unit_categor_b55975_idx"
            ),
        ),
    ]
