import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        (
            "characters",
            "0002_borsareagenti_equip_faretra_note_personaggio_zaino_and_more",
        ),
        ("media_library", "0002_audiofile_datimappa_uploadedimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignloreentry",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lore_entries",
                to="media_library.uploadedimage",
            ),
        ),
        migrations.AddField(
            model_name="daticampagna",
            name="default_global_map",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_campaigns",
                to="media_library.uploadedimage",
            ),
        ),
        migrations.AddField(
            model_name="giocatore",
            name="active_character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_giocatori",
                to="characters.personaggio",
            ),
        ),
        migrations.AddField(
            model_name="guida",
            name="immagine_sfondo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guide",
                to="media_library.uploadedimage",
            ),
        ),
        migrations.AddField(
            model_name="halloffamecharacter",
            name="immagine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hall_of_fame_entries",
                to="media_library.uploadedimage",
            ),
        ),
        migrations.AddField(
            model_name="halloffamecharacter",
            name="personaggio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hall_of_fame_entries",
                to="characters.personaggio",
            ),
        ),
        migrations.AddField(
            model_name="negozio",
            name="citta_immagine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="negozi_citta",
                to="media_library.uploadedimage",
            ),
        ),
        migrations.AddField(
            model_name="negozio",
            name="immagine_sfondo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="negozi_sfondo",
                to="media_library.uploadedimage",
            ),
        ),
        migrations.AddField(
            model_name="negozio",
            name="regione_immagine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="negozi_regione",
                to="media_library.uploadedimage",
            ),
        ),
        migrations.AddField(
            model_name="oggetto",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oggetti",
                to="media_library.uploadedimage",
            ),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="immagine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timeline_events",
                to="media_library.uploadedimage",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="lore_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unit_lore",
                to="media_library.uploadedimage",
            ),
        ),
    ]
