# Generated by Django 5.2.6 on 2026-07-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_hierarchical_settings"),
        ("media_library", "0003_delete_usermediaasset"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="settingdefinition",
            options={
                "ordering": ["category", "order", "key"],
                "verbose_name": "definizione di impostazione",
                "verbose_name_plural": "definizioni delle impostazioni",
            },
        ),
        migrations.AlterModelOptions(
            name="settingoverride",
            options={
                "ordering": ["giocatore__nome", "setting__category", "setting__order"],
                "verbose_name": "preferenza personale",
                "verbose_name_plural": "preferenze personali",
            },
        ),
        migrations.AlterField(
            model_name="giocatore",
            name="role",
            field=models.CharField(
                choices=[("user", "Giocatore"), ("master", "Master"), ("admin", "Amministratore")],
                default="user",
                max_length=20,
                verbose_name="livello di accesso",
            ),
        ),
        migrations.AlterField(
            model_name="settingdefinition",
            name="active",
            field=models.BooleanField(default=True, verbose_name="attiva"),
        ),
        migrations.AlterField(
            model_name="settingdefinition",
            name="category",
            field=models.CharField(max_length=80, verbose_name="categoria"),
        ),
        migrations.AlterField(
            model_name="settingdefinition",
            name="choices",
            field=models.JSONField(blank=True, default=list, verbose_name="scelte disponibili"),
        ),
        migrations.AlterField(
            model_name="settingdefinition",
            name="default_value",
            field=models.JSONField(blank=True, default=dict, verbose_name="valore predefinito"),
        ),
        migrations.AlterField(
            model_name="settingdefinition",
            name="description",
            field=models.TextField(blank=True, verbose_name="descrizione"),
        ),
        migrations.AlterField(
            model_name="settingdefinition",
            name="key",
            field=models.CharField(max_length=160, unique=True, verbose_name="chiave"),
        ),
        migrations.AlterField(
            model_name="settingdefinition",
            name="label",
            field=models.CharField(max_length=180, verbose_name="etichetta"),
        ),
        migrations.AlterField(
            model_name="settingdefinition",
            name="master_customizable",
            field=models.BooleanField(default=False, verbose_name="modificabile dal master"),
        ),
        migrations.AlterField(
            model_name="settingdefinition",
            name="minimum_role",
            field=models.CharField(
                choices=[("user", "Giocatore"), ("master", "Master"), ("admin", "Amministratore")],
                default="user",
                max_length=20,
                verbose_name="livello minimo",
            ),
        ),
        migrations.AlterField(
            model_name="settingdefinition",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="ordine"),
        ),
        migrations.AlterField(
            model_name="settingdefinition",
            name="ui_token",
            field=models.CharField(blank=True, max_length=80, verbose_name="token dell'interfaccia"),
        ),
        migrations.AlterField(
            model_name="settingdefinition",
            name="user_customizable",
            field=models.BooleanField(default=False, verbose_name="modificabile dal giocatore"),
        ),
        migrations.AlterField(
            model_name="settingdefinition",
            name="value",
            field=models.JSONField(blank=True, null=True, verbose_name="valore globale"),
        ),
        migrations.AlterField(
            model_name="settingdefinition",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("bool", "Sì/No"),
                    ("int", "Numero intero"),
                    ("string", "Testo"),
                    ("color", "Colore"),
                    ("select", "Scelta"),
                    ("json", "JSON"),
                ],
                default="string",
                max_length=20,
                verbose_name="tipo di valore",
            ),
        ),
        migrations.AlterField(
            model_name="settingoverride",
            name="giocatore",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="setting_overrides",
                to="core.giocatore",
                verbose_name="giocatore",
            ),
        ),
        migrations.AlterField(
            model_name="settingoverride",
            name="setting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overrides",
                to="core.settingdefinition",
                verbose_name="impostazione",
            ),
        ),
        migrations.AlterField(
            model_name="settingoverride",
            name="value",
            field=models.JSONField(verbose_name="valore personale"),
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("slug", models.SlugField(max_length=80, unique=True, verbose_name="identificatore")),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                ("description", models.TextField(blank=True, verbose_name="descrizione")),
                ("is_active", models.BooleanField(default=True, verbose_name="attivo")),
                ("is_default", models.BooleanField(default=False, verbose_name="predefinito")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordine")),
                ("background_color", models.CharField(default="#f4f2ec", max_length=7, verbose_name="colore di sfondo")),
                ("panel_color", models.CharField(default="#ffffff", max_length=7, verbose_name="colore dei pannelli")),
                ("panel_strong_color", models.CharField(default="#f9faf8", max_length=7, verbose_name="colore dei pannelli in rilievo")),
                ("text_color", models.CharField(default="#202521", max_length=7, verbose_name="colore del testo")),
                ("muted_text_color", models.CharField(default="#6e746e", max_length=7, verbose_name="colore del testo secondario")),
                ("line_color", models.CharField(default="#d8ddd3", max_length=7, verbose_name="colore dei bordi")),
                ("accent_color", models.CharField(default="#2f6f62", max_length=7, verbose_name="colore principale")),
                ("accent_strong_color", models.CharField(default="#214f47", max_length=7, verbose_name="colore principale intenso")),
                ("gold_color", models.CharField(default="#af7d2f", max_length=7, verbose_name="colore dorato")),
                ("sidebar_color", models.CharField(default="#1f2a27", max_length=7, verbose_name="colore del menu laterale")),
                ("overlay_opacity", models.DecimalField(decimal_places=2, default=0.72, help_text="Valore compreso tra 0 e 1. Più è alto, più lo sfondo risulta attenuato.", max_digits=3, verbose_name="opacità del velo sugli sfondi")),
                ("panel_opacity", models.DecimalField(decimal_places=2, default=0.94, help_text="Valore compreso tra 0 e 1.", max_digits=3, verbose_name="opacità dei pannelli")),
                ("background_position", models.CharField(default="center center", help_text="Per esempio: center center, top center oppure 50% 20%.", max_length=80, verbose_name="posizione degli sfondi")),
                ("background_blur", models.PositiveSmallIntegerField(default=0, verbose_name="sfocatura degli sfondi (px)")),
                ("characters_background", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="characters_themes", to="media_library.uploadedimage", verbose_name="sfondo selezione personaggi")),
                ("dashboard_background", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dashboard_themes", to="media_library.uploadedimage", verbose_name="sfondo menu principale")),
                ("dice_background", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dice_themes", to="media_library.uploadedimage", verbose_name="sfondo area dadi")),
                ("guide_background", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="guide_themes", to="media_library.uploadedimage", verbose_name="sfondo guide")),
                ("journal_background", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="journal_themes", to="media_library.uploadedimage", verbose_name="sfondo diario")),
                ("media_background", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="media_themes", to="media_library.uploadedimage", verbose_name="sfondo archivio multimediale")),
                ("personaggio_background", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="personaggio_themes", to="media_library.uploadedimage", verbose_name="sfondo scheda personaggio")),
                ("settings_background", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="settings_themes", to="media_library.uploadedimage", verbose_name="sfondo impostazioni")),
            ],
            options={
                "verbose_name": "tema",
                "verbose_name_plural": "temi",
                "ordering": ["order", "name"],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(is_default=True), fields=("is_default",), name="one_default_theme"),
                    models.CheckConstraint(condition=models.Q(overlay_opacity__gte=0, overlay_opacity__lte=1), name="theme_overlay_opacity_between_zero_and_one"),
                    models.CheckConstraint(condition=models.Q(panel_opacity__gte=0, panel_opacity__lte=1), name="theme_panel_opacity_between_zero_and_one"),
                ],
            },
        ),
    ]
