# Generated by Django 5.2.6 on 2026-07-10

import django.core.validators
from django.db import migrations, models


COLOR_VALIDATOR = django.core.validators.RegexValidator(
    message="Inserisci un colore esadecimale nel formato #RRGGBB.",
    regex=r"^#[0-9a-fA-F]{6}$",
)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_theme_and_italian_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="accent_color",
            field=models.CharField(default="#2f6f62", max_length=7, validators=[COLOR_VALIDATOR], verbose_name="colore principale"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="accent_strong_color",
            field=models.CharField(default="#214f47", max_length=7, validators=[COLOR_VALIDATOR], verbose_name="colore principale intenso"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="background_blur",
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)], verbose_name="sfocatura degli sfondi (px)"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="background_color",
            field=models.CharField(default="#f4f2ec", max_length=7, validators=[COLOR_VALIDATOR], verbose_name="colore di sfondo"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="gold_color",
            field=models.CharField(default="#af7d2f", max_length=7, validators=[COLOR_VALIDATOR], verbose_name="colore dorato"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="line_color",
            field=models.CharField(default="#d8ddd3", max_length=7, validators=[COLOR_VALIDATOR], verbose_name="colore dei bordi"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="muted_text_color",
            field=models.CharField(default="#6e746e", max_length=7, validators=[COLOR_VALIDATOR], verbose_name="colore del testo secondario"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="panel_color",
            field=models.CharField(default="#ffffff", max_length=7, validators=[COLOR_VALIDATOR], verbose_name="colore dei pannelli"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="panel_strong_color",
            field=models.CharField(default="#f9faf8", max_length=7, validators=[COLOR_VALIDATOR], verbose_name="colore dei pannelli in rilievo"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="sidebar_color",
            field=models.CharField(default="#1f2a27", max_length=7, validators=[COLOR_VALIDATOR], verbose_name="colore del menu laterale"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="text_color",
            field=models.CharField(default="#202521", max_length=7, validators=[COLOR_VALIDATOR], verbose_name="colore del testo"),
        ),
    ]
