# Generated by Django 5.2.15 on 2026-07-10 23:33

import django.core.validators
from django.db import migrations, models


def seed_character_inventory_capacity(apps, schema_editor):
    GlobalModifiers = apps.get_model("core", "GlobalModifiers")
    profile = GlobalModifiers.objects.filter(name="Formule_base").first()
    if profile is None:
        return
    values = dict(profile.value_float or {})
    if int(values.get("slot_magici", 0) or 0) == 0 and int(values.get("slot_non_magici", 0) or 0) == 0:
        values["slot_magici"] = 4
        values["slot_non_magici"] = 12
        profile.value_float = values
        profile.save(update_fields=["value_float"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_theme_validation"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="energy_color",
            field=models.CharField(
                default="#4f8a58",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Inserisci un colore esadecimale nel formato #RRGGBB.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
                verbose_name="colore energia",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="health_color",
            field=models.CharField(
                default="#a63d40",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Inserisci un colore esadecimale nel formato #RRGGBB.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
                verbose_name="colore punti ferita",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="invalid_slot_color",
            field=models.CharField(
                default="#a63d40",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Inserisci un colore esadecimale nel formato #RRGGBB.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
                verbose_name="colore slot incompatibile",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="mana_color",
            field=models.CharField(
                default="#3f6fa9",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Inserisci un colore esadecimale nel formato #RRGGBB.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
                verbose_name="colore mana",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="power_color",
            field=models.CharField(
                default="#7653a6",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Inserisci un colore esadecimale nel formato #RRGGBB.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
                verbose_name="colore potere",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="valid_slot_color",
            field=models.CharField(
                default="#4f8a58",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Inserisci un colore esadecimale nel formato #RRGGBB.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
                verbose_name="colore slot compatibile",
            ),
        ),
        migrations.RunPython(seed_character_inventory_capacity, migrations.RunPython.noop),
    ]
