# Generated by Django 5.2.15 on 2026-07-17 11:56

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def normalize_existing_skills(apps, schema_editor):
    Skill = apps.get_model("core", "Skill")
    aliases = {
        "tutti": "all",
        "tutto": "all",
        "generali": "general",
        "rossi": "red",
        "verdi": "green",
        "blu": "blue",
    }
    used = set()
    for skill in Skill.objects.order_by("id"):
        base = slugify(skill.nome) or f"skill-{skill.id}"
        candidate = base[:180]
        suffix = 2
        while candidate in used:
            candidate = f"{base[:174]}-{suffix}"
            suffix += 1
        used.add(candidate)
        skill.slug = candidate
        skill.tipo_pe = aliases.get(str(skill.tipo_pe or "").strip().lower(), "all")
        skill.save(update_fields=["slug", "tipo_pe"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_theme_energy_color_theme_health_color_and_more"),
        ("media_library", "0004_uploadedimage_group_imagecategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="famigliaskill",
            name="immagine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="famiglie_skill",
                to="media_library.uploadedimage",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="azioni_attive",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="skill",
            name="effetti_passivi",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="skill",
            name="icona",
            field=models.CharField(blank=True, default="runa", max_length=80),
        ),
        migrations.AddField(
            model_name="skill",
            name="livello_minimo",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="skill",
            name="prerequisiti",
            field=models.ManyToManyField(
                blank=True, related_name="sblocca_skills", to="core.skill"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="riassunto",
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name="skill",
            name="slug",
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.RunPython(normalize_existing_skills, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="skill",
            name="slug",
            field=models.SlugField(max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="tipo_pe",
            field=models.CharField(
                choices=[
                    ("all", "Tutti"),
                    ("general", "Generali"),
                    ("red", "Rossi"),
                    ("green", "Verdi"),
                    ("blue", "Blu"),
                ],
                default="all",
                max_length=40,
            ),
        ),
    ]
