# Generated by Django 5.2.15 on 2026-07-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_famigliaskill_immagine_skill_azioni_attive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="famigliaskill",
            name="gruppo",
            field=models.CharField(
                choices=[
                    ("Generali", "Generali"),
                    ("Religioni", "Religioni"),
                    ("Scuole di Magia", "Scuole di Magia"),
                    ("Classi", "Classi"),
                    ("Perk", "Perk"),
                ],
                default="Generali",
                max_length=80,
            ),
        ),
    ]
