# Generated by Django 5.2.15 on 2026-07-17 19:25

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def migrate_spells_and_archive_poc(apps, schema_editor):
    Skill = apps.get_model("core", "Skill")
    SpellDefinition = apps.get_model("core", "SpellDefinition")
    tier_aliases = {
        "base": "base",
        "novizio": "base",
        "apprendista": "apprentice",
        "maestro": "master",
    }
    for skill in Skill.objects.filter(magia=True).iterator():
        SpellDefinition.objects.get_or_create(
            skill_id=skill.id,
            defaults={
                "tier": tier_aliases.get((skill.livello_magia or "").strip().lower(), "base"),
                "range_text": skill.raggio or "",
                "effect_unit": "Effetto",
                "base_mana": 0,
                "effect_per_mana": 1,
                "minimum_mana": 0,
                "rounding": "none",
                "legacy_formula": skill.formula_effetto or "",
                "cost_notes": skill.costo_testuale or "",
                "combat_configuration": {"prepared": True, "spendsResources": False},
                "metadata": {"source": "core.0011_legacy_magic_fields"},
            },
        )
    Skill.objects.filter(nome__startswith="POC -", archived_at__isnull=True).update(
        archived_at=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_famigliaskill_gruppo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpellDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("base", "Base"),
                            ("apprentice", "Apprendista"),
                            ("master", "Maestro"),
                        ],
                        default="base",
                        max_length=24,
                    ),
                ),
                ("range_text", models.CharField(blank=True, max_length=160)),
                ("effect_unit", models.CharField(default="Effetto", max_length=120)),
                (
                    "base_mana",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "effect_per_mana",
                    models.DecimalField(decimal_places=6, default=1, max_digits=12),
                ),
                (
                    "minimum_mana",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "rounding",
                    models.CharField(
                        choices=[
                            ("none", "Nessun arrotondamento"),
                            ("floor", "Per difetto"),
                            ("ceil", "Per eccesso"),
                            ("nearest", "Al più vicino"),
                        ],
                        default="none",
                        max_length=24,
                    ),
                ),
                ("legacy_formula", models.CharField(blank=True, max_length=255)),
                ("cost_notes", models.TextField(blank=True)),
                ("combat_configuration", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": [
                    "skill__famiglia__ordine",
                    "tier",
                    "skill__ordine_famiglia",
                    "skill__nome",
                ],
            },
        ),
        migrations.AddField(
            model_name="spelldefinition",
            name="skill",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spell_definition",
                to="core.skill",
            ),
        ),
        migrations.RunPython(migrate_spells_and_archive_poc, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="skill",
            name="core_skill_magia_a5631a_idx",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="formula_effetto",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="livello_magia",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="livello_minimo",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="magia",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="raggio",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="riassunto",
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["tipo_pe"], name="core_skill_tipo_pe_779925_idx"
            ),
        ),
    ]
