# Generated by Django 5.2.15 on 2026-07-17 19:57

from django.db import migrations


def seed_skill_pricing_config(apps, schema_editor):
    GlobalModifiers = apps.get_model("core", "GlobalModifiers")
    profile = GlobalModifiers.objects.filter(name="Formule_base").first()
    if profile is None:
        return
    value_string = dict(profile.value_string) if isinstance(profile.value_string, dict) else {}
    if "skill_pricing" in value_string:
        return
    value_string["skill_pricing"] = {
        "modifier_base": 3,
        "modifier_max": 9,
        "scaling_factor": 0.7,
        "scaling_divisor": 1.5,
        "spent_xp_discount_cap": 100,
    }
    profile.value_string = value_string
    profile.save(update_fields=["value_string", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_spelldefinition_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_skill_pricing_config, migrations.RunPython.noop),
    ]
