# Generated by Django 5.2.15 on 2026-07-22 10:04

import django.core.validators
from django.db import migrations, models


def seed_alchemy_reagents(apps, schema_editor):
    ReagenteAlchemico = apps.get_model("core", "ReagenteAlchemico")
    from backend.core.alchemy_defaults import ALCHEMY_REAGENT_DEFAULTS

    for order, (name, color, level) in enumerate(ALCHEMY_REAGENT_DEFAULTS, start=1):
        ReagenteAlchemico.objects.get_or_create(
            nome=name,
            defaults={
                "colore": color,
                "livello": level,
                "attivo": True,
                "ordine": order,
                "metadata": {
                    "seed_kind": "elder_alchemy_reagent",
                    "seed_version": "1",
                },
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_characterassignmentrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReagenteAlchemico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("nome", models.CharField(max_length=160, unique=True)),
                (
                    "colore",
                    models.CharField(
                        choices=[
                            ("rosso", "Rosso"),
                            ("verde", "Verde"),
                            ("blu", "Blu"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "livello",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                ("attivo", models.BooleanField(default=True)),
                ("ordine", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "reagente alchemico",
                "verbose_name_plural": "reagenti alchemici",
                "ordering": ["ordine", "livello", "nome"],
                "indexes": [
                    models.Index(
                        fields=["attivo", "colore", "livello"],
                        name="core_reagen_attivo_3d4d21_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("livello__gte", 1), ("livello__lte", 4)),
                        name="alchemy_reagent_level_1_to_4",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_alchemy_reagents, migrations.RunPython.noop),
    ]
