# Generated by Django 5.2.15 on 2026-07-22 17:24

import django.core.validators
from django.db import migrations, models


def seed_current_item_type_options(apps, schema_editor):
    Oggetto = apps.get_model("core", "Oggetto")
    OpzioneTipoOggetto = apps.get_model("core", "OpzioneTipoOggetto")
    for posizione in range(1, 5):
        values = (
            Oggetto.objects.exclude(**{f"tipo_{posizione}": ""})
            .values_list(f"tipo_{posizione}", flat=True)
            .distinct()
        )
        for ordine, value in enumerate(sorted({str(entry).strip() for entry in values if entry}), start=10):
            OpzioneTipoOggetto.objects.get_or_create(
                posizione=posizione,
                valore=value,
                defaults={"etichetta": value, "ordine": ordine},
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alchemy_reagent_catalog"),
        ("media_library", "0004_uploadedimage_group_imagecategory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpzioneTipoOggetto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "posizione",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Tipo 1"),
                            (2, "Tipo 2"),
                            (3, "Tipo 3"),
                            (4, "Tipo 4"),
                        ]
                    ),
                ),
                ("valore", models.CharField(max_length=80)),
                ("etichetta", models.CharField(blank=True, max_length=120)),
                ("attiva", models.BooleanField(default=True)),
                ("ordine", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "opzione tipo oggetto",
                "verbose_name_plural": "opzioni tipo oggetto",
                "ordering": ["posizione", "ordine", "etichetta", "valore"],
            },
        ),
        migrations.RunPython(seed_current_item_type_options, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="oggetto",
            name="tipo_5",
        ),
        migrations.RemoveField(
            model_name="oggetto",
            name="tipo_6",
        ),
        migrations.AddField(
            model_name="oggetto",
            name="effetto_1",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="effetto Elder 1"
            ),
        ),
        migrations.AddField(
            model_name="oggetto",
            name="effetto_2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="effetto Elder 2"
            ),
        ),
        migrations.AddField(
            model_name="oggetto",
            name="effetto_3",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="effetto Elder 3"
            ),
        ),
        migrations.AddField(
            model_name="oggetto",
            name="effetto_4",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="effetto Elder 4"
            ),
        ),
        migrations.AddField(
            model_name="oggetto",
            name="effetto_5",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="effetto Elder 5"
            ),
        ),
        migrations.AddField(
            model_name="oggetto",
            name="effetto_6",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="effetto Elder 6"
            ),
        ),
        migrations.AddField(
            model_name="oggetto",
            name="effetto_7",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="effetto Elder 7"
            ),
        ),
        migrations.AddField(
            model_name="oggetto",
            name="effetto_8",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="effetto Elder 8"
            ),
        ),
        migrations.AlterField(
            model_name="oggetto",
            name="rarita",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Unico"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                ],
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="oggetto",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rarita__isnull", True),
                    models.Q(("rarita__gte", 0), ("rarita__lte", 5)),
                    _connector="OR",
                ),
                name="item_rarity_unique_or_1_to_5",
            ),
        ),
        migrations.AddIndex(
            model_name="opzionetipooggetto",
            index=models.Index(
                fields=["posizione", "attiva", "ordine"],
                name="core_opzion_posizio_816a51_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="opzionetipooggetto",
            constraint=models.UniqueConstraint(
                fields=("posizione", "valore"),
                name="unique_item_type_option_per_position",
            ),
        ),
    ]
