# Generated by Django 5.2.15 on 2026-07-22 21:17

import django.db.models.deletion
from django.db import migrations, models


def rename_test_campaign(apps, schema_editor):
    DatiCampagna = apps.get_model("core", "DatiCampagna")
    Giocatore = apps.get_model("core", "Giocatore")
    campaign = DatiCampagna.objects.filter(nome="Campagna principale").order_by("id").first()
    if campaign is None:
        campaign = DatiCampagna.objects.filter(nome="Campagna Test").order_by("id").first()
    if campaign is None:
        return
    if campaign.nome != "Campagna Test":
        campaign.nome = "Campagna Test"
        campaign.save(update_fields=["nome"])
    Giocatore.objects.filter(active_campaign__isnull=True).update(active_campaign=campaign)


def restore_campaign_name(apps, schema_editor):
    DatiCampagna = apps.get_model("core", "DatiCampagna")
    DatiCampagna.objects.filter(nome="Campagna Test").update(nome="Campagna principale")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_oggetto_speciale"),
    ]

    operations = [
        migrations.AddField(
            model_name="daticampagna",
            name="note_condivise",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="giocatore",
            name="active_campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_giocatori",
                to="core.daticampagna",
            ),
        ),
        migrations.AlterField(
            model_name="daticampagna",
            name="meteo",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(rename_test_campaign, restore_campaign_name),
    ]
