# Generated by Django 5.2.15 on 2026-07-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_daticampagna_note_condivise_and_more"),
        ("media_library", "0004_uploadedimage_group_imagecategory_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="daticampagna",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attiva", True)),
                fields=("attiva",),
                name="one_active_campaign",
            ),
        ),
    ]
