# Generated by Django 5.2.6 on 2026-07-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_daticampagna_one_active_campaign"),
        ("media_library", "0004_uploadedimage_group_imagecategory_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unit",
            options={"ordering": ["categoria", "nome"]},
        ),
        migrations.RemoveIndex(
            model_name="unit",
            name="core_unit_categor_b55975_idx",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="archetipo_key",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="preset",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="profilo_equip",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="razza",
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["categoria"], name="core_unit_categor_a4806b_idx"
            ),
        ),
    ]
