# Generated by Django 5.2.15 on 2026-07-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_unit_legacy_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="negozio",
            name="last_restocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="negozio",
            name="location_key",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name="negozio",
            name="stock_revision",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
