# Generated by Django 5.2.15 on 2026-07-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_negozio_last_restocked_at_negozio_location_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="negozio",
            name="in_evidenza",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="negozio",
            name="price_modifier_percent",
            field=models.IntegerField(default=0),
        ),
    ]
