# Generated by Django 5.2.15 on 2026-07-28 06:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_elder_quick_stat_fixed_adjustments"),
        ("media_library", "0005_uploadedimage_visibilita_limitata"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="lore_background",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lore_themes",
                to="media_library.uploadedimage",
                verbose_name="sfondo lore",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="market_background",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="market_themes",
                to="media_library.uploadedimage",
                verbose_name="sfondo mercato",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="accent_color",
            field=models.CharField(
                blank=True,
                default="#2f6f62",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Inserisci un colore esadecimale nel formato #RRGGBB.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
                verbose_name="colore principale",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="gold_color",
            field=models.CharField(
                blank=True,
                default="#af7d2f",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Inserisci un colore esadecimale nel formato #RRGGBB.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
                verbose_name="colore dorato",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="sidebar_color",
            field=models.CharField(
                blank=True,
                default="#1f2a27",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Inserisci un colore esadecimale nel formato #RRGGBB.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
                verbose_name="colore del menu laterale",
            ),
        ),
    ]
