# Generated by Django 5.2.15 on 2026-07-28 07:29

from django.db import migrations, models


def populate_chronological_order(apps, schema_editor):
    TimelineEvent = apps.get_model("core", "TimelineEvent")
    for event in TimelineEvent.objects.all().iterator():
        raw_date = str(event.data_evento or "").strip()
        try:
            chronological_order = int(raw_date)
        except ValueError:
            # Custom fantasy date labels remain readable. Their existing row
            # order is the safest deterministic fallback until an editor
            # assigns an explicit numeric position.
            chronological_order = event.pk
        event.ordine_cronologico = chronological_order
        event.save(update_fields=["ordine_cronologico"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_contrast_outline_levels"),
        ("media_library", "0005_uploadedimage_visibilita_limitata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timelineevent",
            options={"ordering": ["ordine_cronologico", "created_at", "id"]},
        ),
        migrations.RemoveIndex(
            model_name="timelineevent",
            name="core_timeli_campagn_928739_idx",
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="ordine_cronologico",
            field=models.IntegerField(
                default=0,
                help_text="Chiave numerica usata soltanto per ordinare gli eventi nella Timeline del Lore.",
            ),
        ),
        migrations.RunPython(populate_chronological_order, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["campagna", "archived_at", "ordine_cronologico"],
                name="core_timeline_campaign_idx",
            ),
        ),
    ]
