# Generated by Django 5.2.15 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_remove_retired_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="negozio",
            name="generation_profile_key",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
