# Generated by Django 5.2.15 on 2026-07-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_drop_dead_mana_ratio_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="spelldefinition",
            name="fixed_costs",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
