# Generated by Django 5.2.15 on 2026-07-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_market_rarity_five"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SkillMigrationReview",
        ),
    ]
