# Generated by Django 5.2.15 on 2026-07-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_contrast_outline_hint_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="oggetto",
            name="regole_speciali",
            field=models.TextField(
                blank=True,
                help_text="Regole leggibili al tavolo per gli effetti che il sistema non sa calcolare. Compilarle dichiara riviste le voci Elder descrittive attualmente presenti, così l'oggetto smette di essere marcato speciale per quel motivo.",
                verbose_name="regole speciali",
            ),
        ),
    ]
