# Generated by Django 5.2.15 on 2026-07-31 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_theme_surface_backgrounds"),
        ("media_library", "0007_videoclip"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomirazzeinfo",
            name="clip_femminile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="culture_come_clip_femminile",
                to="media_library.videoclip",
            ),
        ),
        migrations.AddField(
            model_name="nomirazzeinfo",
            name="clip_maschile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="culture_come_clip_maschile",
                to="media_library.videoclip",
            ),
        ),
        migrations.AddField(
            model_name="nomirazzeinfo",
            name="immagine_femminile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="culture_come_ritratto_femminile",
                to="media_library.uploadedimage",
            ),
        ),
        migrations.AddField(
            model_name="nomirazzeinfo",
            name="immagine_maschile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="culture_come_ritratto_maschile",
                to="media_library.uploadedimage",
            ),
        ),
        migrations.AddField(
            model_name="nomirazzeinfo",
            name="immagine_razza",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="razze_come_ritratto",
                to="media_library.uploadedimage",
            ),
        ),
    ]
